# Change these first
owner: andyjjrt # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personal Website
    url: https://andyjjrt.cc
  - name: Uptime Kuma
    url: https://uptime.andyjjrt.cc
